name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Install flake8
      run: |
        pip install flake8

    - name: Linting
      run: |
        flake8 Integration_tests.py "Main project automated test suite.py" Test\ project.py

    - name: Build and Test
      run: |
        python -m unittest discover -s tests/

