name: CI/CD

on:
  push:
    branches:
      - main  #

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Specify your desired Python version

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Replace with your dependency installation command

    - name: Linting
      run: |
       flake8 src/ Integration_tests/

    - - name: Build and Test
  run: |
    python Test project.py  
    python -main project automated test suite.py /  


    - name: Deploy
      run: |
        # deploy.sh
  

    - name: Notify on Success
      if: success()
      run: |
#"Build and deployment succeeded! Notify stakeholders."

    - name: Notify on Failure
      if: failure()
      run: |
        #  "Build failed! Notify stakeholders."
