name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Linting
      run: flake8 src/ Integration_tests/

    - name: Build and Test
      run: |
        python -m unittest discover -s tests/
        python main_project.py

    - name: Notify on Success
      if: success()
      run: echo "Build and test succeeded! Notify stakeholders."

    - name: Notify on Failure
      if: failure()
      run: echo "Build or test failed! Notify stakeholders."
